# Generated by Django 4.1 on 2023-07-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Civil_Cad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=150)),
                ("short_paragraph", models.TextField(blank=True)),
                ("long_paragraph", models.TextField(blank=True)),
                ("cad_image", models.ImageField(upload_to="civil_images/")),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(default="", max_length=150)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Elect_Cad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=150)),
                ("short_paragraph", models.TextField(blank=True)),
                ("long_paragraph", models.TextField(blank=True)),
                ("cad_image", models.ImageField(upload_to="elect_images/")),
            ],
        ),
        migrations.CreateModel(
            name="Mech_Cad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=150)),
                ("short_paragraph", models.TextField(blank=True)),
                ("long_paragraph", models.TextField(blank=True)),
                ("cad_image", models.ImageField(upload_to="mech_images/")),
            ],
        ),
        migrations.CreateModel(
            name="Train_Cad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=150)),
                ("short_paragraph", models.TextField(blank=True)),
                ("long_paragraph", models.TextField(blank=True)),
                ("cad_image", models.ImageField(upload_to="train_images/")),
            ],
        ),
    ]
